### ISSUE TITLE
Functionality 5. Admin plug-in restoring a category does not display a source category search engine feature as it appears when restoring a course

### ISSUE THREAD

**Issue by mapemo4** [UNIMOODLE/moodle-local_coursetransfer#23]
![image003](https://github.com/UNIMOODLE/moodle-local_coursetransfer/assets/157824055/b68fe8f4-da3e-4105-a111-d6b6b9fe6390)
When restoring a category, a source category search engine is not displayed as it is shown when restoring a course.

**Comment by xpazv** [comment]
The functionality to restore a category is not aimed for Administrators, but rather to users who do not have access to the site administration functionalities.

A use case could be the following:

- A primary cycle coordinator wants to bring all the courses in the First Cycle of Primary category from a platform from the previous year.
- This user has access to this year's First Cycle of Primary category, so they go there and click on Restore Remote Category. Therefore, the DESTINATION...ALWAYS...will be that category, because that user is in that context and it is about bringing the restorations to that category in a controlled manner.

The other, more powerful functionality of the site administration, where you can restore categories and courses, is aimed only at Administrators, and that is why they can select the destinations. 

An administrator could use the functionality within the categories, but it is not aimed at them, since it is not widely used.

**Comment by AngelAyllon** [comment]
OK. I understand what you're saying. The administrator must restore categories from the administration extensions but not from courses and categories.
